# sudo required for installing dependencies of Scala Native
sudo: required
dist: bionic

language: scala
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.8
  - 2.13.0

before_install:
  - sudo rm -r /usr/local/clang-7.0.0
  - sudo apt-get update
  - sudo apt-get install -y libre2-dev libunwind-dev clang nodejs openjdk-8-jdk-headless

env:
  -JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

script:
  - sbt -java-home /usr/lib/jvm/java-8-openjdk-amd64 ++$TRAVIS_SCALA_VERSION test mimaReportBinaryIssues

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -rf $HOME/.ivy2/{cache,local}/io.spray/

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
